runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: MySQLdb
  version: "latest"

handlers:
- url: /.*
  script: main.app

env_variables:
    CLOUDSQL_CONNECTION_NAME: shareurl-007:asia-east1:sharedsql
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: root12
    CLOUDSQL_DATABASE: Bucket